services:
    node:
        container_name: node_api_c
        build: "./server/"
        ports:
          - "5000:5000"
        env_file:
            - ./server/.env
        networks:
            - initiation
        depends_on:
            - mysql
        restart: always
    nginx:
        container_name: nginx_c
        build: "./client/"
        env_file:
            - ./client/.env 
        ports:
            - "80:80"
        networks:
            - initiation
        restart: always
    portainer:
        container_name: portainer_c
        image: portainer/portainer
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        ports:
            - "9443:9443"
        networks:
            - initiation
        restart: always
    mysql:
        container_name: mysql_c
        build: "./mysql/"
        env_file:
            - ./server/.env
        ports:
          - "3306:3306"
        networks:
            - initiation
        volumes:
          - mysql_data:/var/lib/mysql
        restart: always

volumes:
    portainer_data:
        name: portainer
        driver: local
        driver_opts:
            type: none
            device: ./volume/portainer
            o: bind
    mysql_data:
        name: mysql
        driver: local
        driver_opts:
            type: node
            device: ./volume/mysql
            o: bind

networks:
    initiation:
        name: initiation
        driver: "bridge"