### Registration Request
POST http://localhost:5000/api/registration HTTP/1.1
Host: localhost
Content-Type: application/json

{
	"email": "fantom.assasinnnn@mail.ru",
	"password": "1234"
}

### Login Request
POST http://localhost:5000/api/login HTTP/1.1
Host: localhost
Content-Type: application/json

{
	"email": "armanmartirosyan81@gmail.com",
	"password": "1234"
}

### Refresh Request
GET http://localhost:5000/api/refresh HTTP/1.1
Host: localhost
Content-Type: application/json


### Logout Request
POST http://localhost:5000/api/logout HTTP/1.1
Host: localhost
Content-Type: application/json


### Get Users Request
GET http://localhost:5000/api/users HTTP/1.1
Host: localhost
Content-Type: application/json
Authorization: Bearer ceyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhbnRvbS5hc3Nhc2lubm5uQG1haWwucnUiLCJpZCI6MSwiaXNBY3RpdmF0ZWQiOjEsImlhdCI6MTcxODM3MzA3MywiZXhwIjoxNzE4MzczMTAzfQ.aIP3nvQDYTHxdVSqpiVwfvGWZ-8Xneiu_fImcjSt1T4